/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package usandojtable;

import java.awt.Color;
import java.awt.Font;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author B30
 */
public class Tabela2 extends javax.swing.JFrame {

    /**
     * Creates new form Tabela2
     */
    public Tabela2() {
        initComponents();
        montaTabela();
    }
    
    
    public void montaTabela(){
        
        //Cria modelo padrão a ser seguido pela tabela
        DefaultTableModel modelo = new DefaultTableModel(){
        public Class getColumnClass(int coluna){
            return coluna==0?Icon.class:Object.class;
        }
            
        };
        ImageIcon verde = new ImageIcon("C:\\Users\\B30\\Documents\\NetBeansProjects\\UsandoJTable\\src\\usandojtable\\verde.png");
        //cabecalhosdascolunas
        
        modelo.setColumnIdentifiers(new String []{"Titulo 1","Titulo 2","Titulo 3"});
        
        tbExemplo.setModel(modelo);
        tbExemplo.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tbExemplo.getColumnModel().getColumn(0).setPreferredWidth(176);
        tbExemplo.getColumnModel().getColumn(1).setPreferredWidth(176);
        tbExemplo.getColumnModel().getColumn(2).setPreferredWidth(176);
    
        
        for (int i = 0; i < 10; i++) {
            modelo.addRow(new Object[]{verde,"Col1"+i,"Col2"+(i+1),"Col3"+(i+2)});
        }
        
        //grid
        
        tbExemplo.setShowGrid(true);
        //nao permite selecao de mais de um item
        
        tbExemplo.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        //ajusta a altura da  tabela conforme a frame
        tbExemplo.setFillsViewportHeight(true);
        //cor do fundo da tabela
        tbExemplo.setBackground(new Color(0,0,0));
        //cor da letra
        tbExemplo.setForeground(new Color(255,255,255));
        
        //cor do grid
        
        tbExemplo.setGridColor(new Color(255,0,0));
        
        //cor do foco
        
        tbExemplo.setSelectionBackground(new Color(0,255,0));
        
        //cor de fundo
        
        tbExemplo.setSelectionBackground(new Color(100,125,2));
        
        //altura da celula
        
        tbExemplo.setRowHeight(60);
        
        tbExemplo.setFont(new Font("Impact",0,13));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbExemplo = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbExemplo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbExemplo);

        jButton1.setText("Botao");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println(tbExemplo.getSelectedRow());
        System.out.println(tbExemplo.getValueAt(tbExemplo.getSelectedRow(), 0));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tabela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tabela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tabela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tabela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tabela2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbExemplo;
    // End of variables declaration//GEN-END:variables
}
